### ISSUE TITLE
Stone bricks are unsupported Blocks

### ISSUE THREAD

**Issue by TheNitrogenOxid** [RavinMaddHatter/Structura#100]
Hey stone bricks and stone brick varients are unsupported .

**Comment by RavinMaddHatter** [comment]
Are you sure it isnt infested stone bricks?

**Comment by lenuspenoos** [comment]
Smooth stone bricks arent working for me right now

**Comment by lenuspenoos** [comment]
There is an unsuported block in this world and it was skipped
x:19 Y:10 Z:24, Block:minecraft:stonebrick, Variant: ['stone_brick_type', String('smooth')]

**Comment by RavinMaddHatter** [comment]
There is a method to fix that in the 1.3 video. But it takes time and
energy.

**Comment by RavinMaddHatter** [comment]
Fixed in 1.5
