### ISSUE TITLE
Deepslate?

### ISSUE THREAD

**Issue by TCGamers23** [RavinMaddHatter/Structura#106]
I am trying to use this for my base on NexCraft SMP and it said there was an error with deepslate, I did it with blocks already in the game and it was fine, could you update this so I can use this more? I would really appreciate it! I hope you have a fantastic day!
Thank You
TCGamers

**Comment by RavinMaddHatter** [comment]
Are you using the 1.4 version that has deepslate support? https://ravinmaddhatter.com/2021/07/27/structura-1-4/
I did test it, however if you are using old version there is nothing i can do to fix them.
