### ISSUE TITLE
Glass panes are converted/rendered as full glass blocks.

### ISSUE THREAD

**Issue by omnoms** [RavinMaddHatter/Structura#108]
![](https://user-images.githubusercontent.com/7261863/129038908-d233888a-6c5a-4c65-ad73-74bd0fc5671a.png)

Actual structure  
  
  
Structura loaded structure  
 

![](https://user-images.githubusercontent.com/7261863/129038862-849866f7-27c6-45aa-b4ad-1108c9a940d3.png)

**Comment by RavinMaddHatter** [comment]
I appreciate the quantity bug report... But that is fixed... 2 versions ago

**Comment by RavinMaddHatter** [comment]
It was fixed in 1.3. 1.4 has an "update blocks" button

**Comment by omnoms** [comment]
Ah, I thought I was on the latest release (since only one was on the list) but it was a release specific link on the youtube description to the old one. Closing this one!
