### ISSUE TITLE
Error when using the structura.exe

### ISSUE THREAD

**Issue by lenuspenoos** [RavinMaddHatter/Structura#114]
I get an error code saying 
Exception in Tkinter callback Traceback (most recent call last): File "structura.py", line 96, in generate_pack File "armor_stand_class.py", line 74, in make_block File "armor_stand_class.py", line 330, in block_name_to_uv File "armor_stand_class.py", line 388, in get_block_texture_paths KeyError: String('smooth') During handling of the above exception, another exception occurred: Traceback (most recent call last): File "tkinter\__init__.py", line 1883, in __call__ File "structura.py", line 161, in runFromGui File "structura.py", line 99, in generate_pack File "armor_stand_class.py", line 74, in make_block File "armor_stand_class.py", line 330, in block_name_to_uv File "armor_stand_class.py", line 388, in get_block_texture_paths KeyError: String('smooth')

**Comment by RavinMaddHatter** [comment]
Are you using the latest version (1.4) as the old version doesn't support
many blocks

**Comment by vanilit** [comment]
hi I'm also having this same error and I've made sure I'm on the latest 1.4 version

**Comment by RavinMaddHatter** [comment]
Do you have smooth stone double slabs in your build? They are a broken block

**Comment by vanilit** [comment]
switching the block worked! thank you so much! and great job on this project, it's very interesting and useful <3
