### ISSUE TITLE
Add condition for rendering structure [Feature Request]

### ISSUE THREAD

**Issue by AvgZing** [RavinMaddHatter/Structura#116]
Consider adding an item (such as a banner) to prevent the armor stand from displaying the structure unless said item is held -- thus making the pack significantly more multiplayer-friendly. One example of this is in FoxyNoTail's markers pack https://foxynotail.com/resource-packs/markers/, though that detects the banners via a pre-animation ```"pre_animation": [
					"variable.marker_sphere = query.get_equipped_item_name('main_hand') == 'banner' && variable.armor_stand.pose_index == 1;",``` and I'm not sure if this addon would support that, but if it is a simple change, it could drastically improve the addon!

**Comment by RavinMaddHatter** [comment]
Does the name tag work for you?

**Comment by AvgZing** [comment]
That would be marginally less survival friendly, but it'd still function -- any item would. The specific item doesn't matter, just any way to separate rendering of the structure from standard decorative armor stands. 

Unless you're referring to nametag as a preexisting feature in structura, in which case, I haven't heard of that feature.

**Comment by RavinMaddHatter** [comment]
You can in the advanced settings name tag armor stands and make multiple
structures in one file. This was added in 1.2 I recommend the latest
release that includes a block definition updater

**Comment by AvgZing** [comment]
Thanks! Totally missed that feature. With how much I use Structura, you'd think I'd have dove into advanced features more.
