### ISSUE TITLE
Error when making file

### ISSUE THREAD

**Issue by HQ3T** [RavinMaddHatter/Structura#117]
error codes:
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1883, in __call__
  File "structura.py", line 161, in runFromGui
  File "structura.py", line 25, in generate_pack
  File "manifest.py", line 33, in export
  File "os.py", line 223, in makedirs
PermissionError: [WinError 5] Accesso negato: 'Tree Farm'

**Comment by HQ3T** [comment]
Thanks

**Comment by RavinMaddHatter** [comment]
Same solution should work. Windows won't let structura access your file.
You need to move the file to a place that structura can access

**Comment by RavinMaddHatter** [comment]
Where is that folder

**Comment by Hellothere1234627284yehnsndnsnwnd** [comment]
In hard disc D

**Comment by RavinMaddHatter** [comment]
What are the permission for d? I know for the c drive it requires admin to
write. It can be the same for other drives. Try my documents

**Comment by Hellothere1234627284yehnsndnsnwnd** [comment]
I put the structura and the structure file there but it says the same again

**Comment by RavinMaddHatter** [comment]
Did you put all the files there?

**Comment by Hellothere1234627284yehnsndnsnwnd** [comment]
Am pretty sure
There will be only 4 files right?
3 or structura and 1 of what am making

**Comment by RavinMaddHatter** [comment]
Um no you should have a bunch of files, and you have to unzip the
structural package.

The release contains a few folders full of files

**Comment by RavinMaddHatter** [comment]
It is in structural chat and it requires some advanced debug skills

**Comment by Hellothere1234627284yehnsndnsnwnd** [comment]
I'll disturb again if i can't make it work work 😁😁
Just kidding 😆
