### ISSUE TITLE
rendering issues

### ISSUE THREAD

**Issue by Khashenzo** [RavinMaddHatter/Structura#122]
hi thnx for ur amazing work im new to this site and all dont understand programming 
i was wondering if u can update this amazing thing to support 1.19 features cuz currently it renders everything except the new stuffs like mangrove trap door mud bricks etc thnx

**Comment by Wargazm** [comment]
What can be done to get 1.19 support?  Any way that we (the users) can help?

**Comment by RavinMaddHatter** [comment]
A few things would really help, a world that contains every block in every
orientation, would be a huge help but it takes effort

**Comment by Wargazm** [comment]
I'd be happy to do that!  When you say every block in every orientation, what exactly do you mean?  Would I have to do that for, say, mangrove planks (that are the same on all sides) or is that only necessary for blocks that look different based on how you place them (like logs)?

**Comment by Wargazm** [comment]
https://www.dropbox.com/s/cnv5gmetw48hfhw/All_New_1.19_Blocks.mcworld?dl=0

Here, hope this helps.

**Comment by RavinMaddHatter** [comment]
Basically I need ever way that we would want a block to look in a structura
file... So stairs all 8 ways, logs all 3. At some point I have to get that
for every block in the game.... And it take a bunch of work...
