### ISSUE TITLE
Supports only 1 Armor stand at a time

### ISSUE THREAD

**Issue by RavinMaddHatter** [RavinMaddHatter/Structura#13]
With behavior packs we could add a support for multiple types of overlays in one world

methods:
Name detection
dyeable armor stands

**Comment by FondUnicycle** [comment]
For name detection a behavior pack is not needed. I will look into it, as there is 2 options i can think about, but will need to test them first.

**Comment by RavinMaddHatter** [comment]
Ohh fond, a behavior pack would do 2 additional things
If installed it will allow people to have more than 1 structura pack on at the same time. and a few other nice things.

It will also help us with pack conflicts. IE poseable armor stands..

**Comment by RavinMaddHatter** [comment]
Fixed in 1.1.2 Thanks Fond
