### ISSUE TITLE
Anvils 

### ISSUE THREAD

**Issue by RavinMaddHatter** [RavinMaddHatter/Structura#137]
Broken And roation

**Comment by Machbar24** [comment]
I believe I've got the anvil sorted.  Can someone check it for me?  The textures don't line up but it appears that mojang is rotating textures 90 degrees when applying them at least for the anvil base.  The other issue is Structura renders the bones smaller than the original so everything looks a little out of wack in aggregate.  
[anvil.zip](https://github.com/RavinMaddHatter/Structura/files/12862133/anvil.zip)
![image](https://github.com/RavinMaddHatter/Structura/assets/147423466/72af4fa4-409f-4b7b-95f7-d73b4d22f1e5)

**Comment by RavinMaddHatter** [comment]
I will build you a test app and check it in. It will use the all blocks
structures and world

**Comment by Machbar24** [comment]
Pull request submitted.  Damaged textures do not show but I'm assuming that NBT data will be needed to fix that.
