### ISSUE TITLE
Wrong items are apearering in the item list

### ISSUE THREAD

**Issue by R2leyser** [RavinMaddHatter/Structura#14]
item list that i got:
This is a list of blocks, there is a known issue with variants, all variants are counted together
structure_block: 1
air: 127
hopper: 6
wool: 19
stone_slab: 1
glass: 6
redstone_wire: 6
unpowered_repeater: 6
unlit_redstone_torch: 1
dispenser: 1
unpowered_comparator: 2
powered_repeater: 1
piston: 1
redstone_torch: 1
observer: 1
also stone brick walls are apering in the list as cobble walls

**Comment by RavinMaddHatter** [comment]
These are not wrong items. they are technically correct. that is what minecrafts sees them as, however i do agree there is clean up required here.

**Comment by R2leyser** [comment]
> These are not wrong items. they are technically correct. that is what minecrafts sees them as, however i do agree there is clean up required here.

I used wrong because of the last line there

**Comment by RavinMaddHatter** [comment]
Wrong to me would mean you had a repeater when it actually was a comparator.

**Comment by R2leyser** [comment]
> Wrong to me would mean you had a repeater when it actually was a comparator.

yeah the last thing i said was that stone brick walls show as cobble walls

**Comment by RavinMaddHatter** [comment]
Next update will have this fix in it. The bot on discord has this fix already
