### ISSUE TITLE
No such file or directory: 'Vanilla_Resource_Pack/textures/blocks/grindstone_side.png

### ISSUE THREAD

**Issue by M2DRIVE** [RavinMaddHatter/Structura#148]
no rotation for barrel found
no rotation for barrel found
no rotation for barrel found
no rotation for barrel found
no rotation for barrel found
no rotation for barrel found
no rotation for barrel found
no rotation for barrel found
no rotation for barrel found
no rotation for barrel found
no rotation for barrel found
no rotation for barrel found
no rotation for barrel found
no rotation for barrel found
no rotation for chest found
no rotation for chest found
no rotation for barrel found
no rotation for barrel found
no rotation for chest found
no rotation for fence_gate found
no rotation for chest found
no rotation for fence_gate found
no rotation for barrel found
no rotation for barrel found
no rotation for chest found
no rotation for chest found
no rotation for barrel found
no rotation for barrel found
no rotation for chest found
no rotation for barrel found
no rotation for barrel found
no rotation for barrel found
no rotation for barrel found
no rotation for barrel found
no rotation for wall_sign found
no rotation for wall_sign found
no rotation for wall_sign found
no rotation for carved_pumpkin found
no rotation for pumpkin found
no rotation for wall_sign found
no rotation for wall_sign found
no rotation for pumpkin found
no rotation for carved_pumpkin found
no rotation for wall_sign found
no rotation for wall_sign found
no rotation for wall_sign found
no rotation for barrel found
no rotation for barrel found
no rotation for wall_banner found
no rotation for barrel found
Exception in Tkinter callback
Traceback (most recent call last):
  File "structura.py", line 96, in generate_pack
  File "armor_stand_class.py", line 74, in make_block
  File "armor_stand_class.py", line 337, in block_name_to_uv
  File "armor_stand_class.py", line 302, in extend_uv_image
  File "PIL\Image.py", line 2891, in open
FileNotFoundError: [Errno 2] No such file or directory: 'Vanilla_Resource_Pack/textures/blocks/grindstone_side.png'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tkinter\__init__.py", line 1883, in __call__
  File "structura.py", line 161, in runFromGui
  File "structura.py", line 99, in generate_pack
  File "armor_stand_class.py", line 74, in make_block
  File "armor_stand_class.py", line 337, in block_name_to_uv
  File "armor_stand_class.py", line 302, in extend_uv_image
  File "PIL\Image.py", line 2891, in open
FileNotFoundError: [Errno 2] No such file or directory: 'Vanilla_Resource_Pack/textures/blocks/grindstone_side.png'

**Comment by RavinMaddHatter** [comment]
you are using an old version of structura. this is updated in the latest
