### ISSUE TITLE
Pack causes suffocation damage on newly placed blocks.

### ISSUE THREAD

**Issue by zuluranger17** [RavinMaddHatter/Structura#154]
While using the pack and placing new blocks, I begin to take suffocation damage on the newly placed blocks. I have tested this with and without the pack, and I've concluded that the pack causes this. However, I did experience this bug while playing on a server that is hosted through Shockbyte. So, I tested it on a local world file and did not experience this bug. The last bit of information I have is that this program and the pack I generated was working fine with 1.19.51, so I am not sure if it is simply due to the newest update either.
![Screenshot (233)](https://user-images.githubusercontent.com/125235138/218366201-ceb8f62f-2d86-427f-9a1e-b22f445ea35a.png)

**Comment by RavinMaddHatter** [comment]
This is just a recovery texture pack... That would be a Minecraft bug
