### ISSUE TITLE
Error reading the nbt data

### ISSUE THREAD

**Issue by GiulioCusenza** [RavinMaddHatter/Structura#159]
I am trying to create a schematic, but I get this error in the console:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1921, in __call__
  File "structura.py", line 335, in runFromGui
  File "structura.py", line 99, in generate_pack
  File "structure_reader.py", line 11, in __init__
  File "nbtlib\nbt.py", line 131, in load
  File "nbtlib\nbt.py", line 259, in from_fileobj
  File "nbtlib\nbt.py", line 225, in parse
TypeError: Non-Compound root tags is not supported: <class 'nbtlib.tag.End'>
```
Only the nametags file and some json get generated, but no .mcpack.

The program works fine for another structure I have.

**Comment by GiulioCusenza** [comment]
Sorry, I have edited the issue to make it more representative. The file size appears to be 0KB, I didn't notice. I will retry generating it on MC and let you know right now.

Thank you for your quick reply!

**Comment by RavinMaddHatter** [comment]
Super common problem I need to add an error checker for

**Comment by GiulioCusenza** [comment]
Minecraft keeps exporting it with 0 KB. Do you have a clue why it is so?

**Comment by RavinMaddHatter** [comment]
I have never had that for me but I know many people have had it. I am not
sure how to fix it. Maybe remake the structure block

**Comment by GiulioCusenza** [comment]
I have tried a bunch of things:
- make another, smaller structure block
- change the structure block options
- copy the world into a new one with experimental features
- try to make some structure in another world
Nothing worked, which probably means that the problem is across all worlds and thus version related (1.19.70). I guess we can only wait, or downgrade to a previous version and try there.

Thank you for your help anyway

**Comment by GiulioCusenza** [comment]
It turns out that **structure blocks can fail to export to OneDrive synchronised folders on windows** (Here is the [bug tracker entry](https://bugs.mojang.com/browse/MCPE-41898?filter=22036&jql=project%20%3D%20MCPE%20AND%20resolution%20%3D%20Unresolved%20AND%20text%20~%20%22structure%20export%22%20ORDER%20BY%20created%20DESC)). 

To solve, just export your structures to a non-OneDrive folder (you can move it to your preferred folder after the export).

**Comment by GiulioCusenza** [comment]
@RavinMaddHatter I suggest that you add an error message that provides users with this information if they read an empty file and are on windows
