### ISSUE TITLE
Missing all wool

### ISSUE THREAD

**Issue by jichangping1** [RavinMaddHatter/Structura#160]
Missing all wool、Smooth quartz half brick、Ground granite half brick.

**Comment by RavinMaddHatter** [comment]
This is due to the changes that were made in the latest release. They
changed wool in a way inconsistent with any other block... And they broke
other blocks

**Comment by RavinMaddHatter** [comment]
This is fixed in the discord bot. Will be in next release. Planning to release right after 1.20, but waiting for mojang.
