### ISSUE TITLE
Support old version of minecraft

### ISSUE THREAD

**Issue by wanzh5** [RavinMaddHatter/Structura#163]
For example 1.13 or 1.5, it doesn't work with those versions.

**Comment by RavinMaddHatter** [comment]
No...  There are too many block differences between each version... It
would literally be days of my life to even attempt this...

Every minor version of Minecraft has some charges...

1.19.60, 1.19.70, 1.19.80 all have changes... I don't even support 1.19.70
and 80 right now.... There is 0 chance of me supporting old version. Some
that are literally impossible to support
