### ISSUE TITLE
Unsupported block types (white_wool, spruce_log etc.)

### ISSUE THREAD

**Issue by JohnVanger** [RavinMaddHatter/Structura#164]
Hi there,

first of all I want to say that I really like your tool, it's a great way to build in survival.

However when exporting a structure and then creating the pack, there are blocks missing like wool, different log types etc.

<img width="441" alt="Structura unsupported block types" src="https://github.com/RavinMaddHatter/Structura/assets/132815278/514245b3-54fb-4ea7-b308-cdb7f00a4925">

Is there a way to edit the files so the blocks aren't skipped?

Thanks, Simon

**Comment by JohnVanger** [comment]
I just thought about if it would be possible to not skip the unsupported blocks, but replace them with any working block that people don't often use, for example bedrock. This way we would have the positions of the blocks in the build.

Thanks, Simon

**Comment by RavinMaddHatter** [comment]
These did work in 1.16.200- 1.19.60.
Mojang changed things in 7 different places and is still changing them for
1.20...

**Comment by JohnVanger** [comment]
Okay then it's maybe best to wait until they are done with the changes

**Comment by JohnVanger** [comment]
where can I find your discord? I didn't see anything on your profile

**Comment by RavinMaddHatter** [comment]
It is in all of the YouTube videos. I have not built out my GitHub profile
yet

**Comment by JohnVanger** [comment]
okay I will check them, thanks a lot

**Comment by RavinMaddHatter** [comment]
Fixed in the discord bot, will be fixed in next release. planning for releasing just after 1.20. i will merge in with the 1.20 changes
