### ISSUE TITLE
some bugs

### ISSUE THREAD

**Issue by ck2739046** [RavinMaddHatter/Structura#18]
Some blocks are not correctly shown
![屏幕截图(238)](https://user-images.githubusercontent.com/49937999/105621125-4811aa80-5e3f-11eb-8e47-581abe10a770.png)

Plus could you add tag function?  I often use armor stands in other places, it is a bit inconvenient to have all armor stands displayed model. If this pack only allow armor stands with certain name tag to display models, I would be really grateful!

**Comment by RavinMaddHatter** [comment]
Can you seperate the feature request from the bug report. the feature request will get lost because once i close the bugs i want to close the ticket

**Comment by RavinMaddHatter** [comment]
I am going to close this, all but the bell were fixed.
