### ISSUE TITLE
feature request: tag function

### ISSUE THREAD

**Issue by ck2739046** [RavinMaddHatter/Structura#19]
Plus could you add tag function?  I often use armor stands in other places, it is a bit inconvenient to have all armor stands displayed model. If this pack only allow armor stands with certain name tag to display models, I would be really grateful!

**Comment by RavinMaddHatter** [comment]
I have a bit of a plan on this. I cannot detect a tag without behavior pack... If i am adding a behavior pack i think i will add "colored armor stands" where you dye an armor stand to a color to get your structure to show up (ie put an armor stand in a crafting menu with blue die and you would get a "blue channel" armor stand.

**Comment by Rayth** [comment]
Maybe instead of adding a behavior pack (because a lot of people will use this in survival only worlds to copy creative builds and want achievements) you could add an option to select from a list of block entities rather than defaulting to armor stand?

**Comment by FondUnicycle** [comment]
It is possible to make it so the armor stand needs to be given a specific name with a name tag to make it show the blocks. That way there's no need of a behavior pack.

**Comment by RavinMaddHatter** [comment]
I am also adding the behavior pack epic to this as there is a case where if a server already has specific behavior packs it will overwrite your resource pack

**Comment by RavinMaddHatter** [comment]
Fixed in 1.1.2 Thanks Fond
