### ISSUE TITLE
"daylight sensor" is misspelled as "dalight sensor" in block list.

### ISSUE THREAD

**Issue by tastyTurncoat** [RavinMaddHatter/Structura#196]
The misspelling is in Structura/lookups/material_list_names.json at line 152.

**Comment by RavinMaddHatter** [comment]
Thank you for that. I had to hand type the block names I will get it fixed
soon

**Comment by tastyTurncoat** [comment]
I found another. "cornflower" is misspelled as "corneflower".

**Comment by JangoBritt** [comment]
Waxed Weathered Copper _Blcok_
Tiled _Deeplsate_ Stairs
