### ISSUE TITLE
oak_fence, dark_oak_log, colored concrete + possible solutions 

### ISSUE THREAD

**Issue by Maelclou11** [RavinMaddHatter/Structura#198]
![image](https://github.com/RavinMaddHatter/Structura/assets/89790435/a7901031-2c6f-4bc8-ae92-1741542a4ced), i noticed that a lot of issu with unknown block was reported so idk if it would be possible but maybe to replace all block that are unknown, place a bloc with red and black texture so at least we can still create the mcpack and see our build without the unknown block, also thank you for your work men this project is insanely helpfull and your a genius.

**Comment by rideronthest0rm** [comment]
Yes colored concrete blocks are not working in the latest version.

**Comment by RavinMaddHatter** [comment]
These are due to changes that Mojang making. As a solo developer it is hard
to keep up with their monthly updates that change random stuff

**Comment by rideronthest0rm** [comment]
I understand and I have tons of respect of you pulling this off, on your own you changed my Minecraft building life! :) Is there anything we can do to help you? Is it hard to update the files so missing blocks are included in the next update?
