### ISSUE TITLE
Feature Request - A Custom Specific Item Loads a Specific Structure

### ISSUE THREAD

**Issue by Ryank414** [RavinMaddHatter/Structura#200]
The idea is similar to [Foxynotails Markers Pack Resource Pack](https://foxynotail.com/resource-packs/markers), where with that pack the overlay only displays when an armor stand has a banner equipped. 

Request: Have an option to pick any item as the "banner" to load a specific structure so multiple Structura packs can be loaded at once. 

Examples: I can select Deepslate Bricks for a Deepslate Temple, Cherry Planks for a Cherry wood House, Bamboo for a Bamboo farm, Iron Ingot for a Iron farm etc...

**Comment by RavinMaddHatter** [comment]
Name takes in advanced mode. I don't have a ui forb items and want to
reserve that for future use
