### ISSUE TITLE
Observers,repeaters and comparators aren't rotated properly

### ISSUE THREAD

**Issue by Nobody2000IQ** [RavinMaddHatter/Structura#204]
Observers are always facing the same direction and same goes for repeaters and comparators

**Comment by RavinMaddHatter** [comment]
Are you using the current version or an ancient one with this bug

**Comment by Nobody2000IQ** [comment]
The latest version 1.6.3

**Comment by RavinMaddHatter** [comment]
Fixed  use the update button to get the fix.
