### ISSUE TITLE
Stained glass, panes, and concrete powder are broken 

### ISSUE THREAD

**Issue by TetianaLitvinova** [RavinMaddHatter/Structura#208]
1.20.30 introduced separate item names for each variant. 
So all stained glass blocks, stained glass panes and concrete powder are not showing in the pack.
![structura_unsupported_blocks](https://github.com/RavinMaddHatter/Structura/assets/41845331/25faaa88-032f-4490-bca2-516b8d683eaf)

**Comment by RavinMaddHatter** [comment]
Was this resolved by your pr?

**Comment by RavinMaddHatter** [comment]
Fixed
