### ISSUE TITLE
Jungle log and fences

### ISSUE THREAD

**Issue by Enc0dek** [RavinMaddHatter/Structura#212]
![image](https://github.com/RavinMaddHatter/Structura/assets/87038378/9786a09e-5cf9-4cc2-8ecd-8a72bf08a554)

![image](https://github.com/RavinMaddHatter/Structura/assets/87038378/349005cf-8ed7-4a97-97d6-baa54098a1f3)

**Comment by RavinMaddHatter** [comment]
Have you used a modern version? Or just old versions?
