### ISSUE TITLE
32 bit version

### ISSUE THREAD

**Issue by FvA-prog** [RavinMaddHatter/Structura#213]
where can I download the 32 bit version of the application?

**Comment by hegehog8761** [comment]
Since 32x systems are not widely used anymore it is not likely that there will not be an official 32x version released however I believe it should be possible to download python for 32x and run the structura.py file

**Comment by RavinMaddHatter** [comment]
Use structura lab if 32 bit version is required. if not use python native. not supporting 2 builds at this time.
