### ISSUE TITLE
`minecraft:chest` is unsupported 

### ISSUE THREAD

**Issue by NickdeK** [RavinMaddHatter/Structura#215]
```
There is an unsuported block in this world and it was skipped
x:12 Y:1 Z:6, Block:minecraft:chest, Variant: default
```

Not sure what the problem is. I do see references in the project, but I'm not familiar with python, so I can't actually debug this.

This happens with any mcstructure file created with the latest minecraft version (1.20.50). Not sure if this was a issue before in older versions or on what version this problem started.

**Comment by RavinMaddHatter** [comment]
Fixed
