### ISSUE TITLE
x:12 Y:4 Z:8, Block:minecraft:spruce_planks, Variant: default There is an unsuported block in this world and it was skipped

### ISSUE THREAD

**Issue by art20042** [RavinMaddHatter/Structura#217]
Not sure what the problem is. I do see references in the project, but I'm not familiar with python, so I can't actually debug this.

This happens with any mcstructure file created with the latest minecraft version (1.20.51). Not sure if this was a before issue in older versions or on what version this problem started.
P.S. I apologize for copying the comment of the person who asked about chests, but I believe the situation is the same, but with spruce boards

**Comment by RavinMaddHatter** [comment]
Mojang changed planks in 1.20.50 and I have not had a chance to fix things
yet

**Comment by RavinMaddHatter** [comment]
Fixed
