### ISSUE TITLE
"Make Pack" Not working

### ISSUE THREAD

**Issue by Pocoyable** [RavinMaddHatter/Structura#221]
I have already download python and all of the other import files. Then, I clicked my structure file. After that, as I clicked Make Pack. I had an error; "[Errno 2] No such file or directory: 'C:\\Users\\user\\Downloads\\StructuraImproved-main\\StructuraImproved-main\\structura\\..\\mcpacks\\xxx.mcpack'", I checked the files and there wasn't a "mcpack" file. How should I troubleshoot this problem?

**Comment by RavinMaddHatter** [comment]
What were you trying to do?

**Comment by Pocoyable** [comment]
I was trying to convert one of my structure files to an mcpack file to use on bedrock, but I couldn't make the mcpack

**Comment by RavinMaddHatter** [comment]
Was it a java file?

**Comment by Pocoyable** [comment]
It wasn't. it is a mcstructure file

**Comment by RavinMaddHatter** [comment]
That would do it

**Comment by Pocoyable** [comment]
But the error still appeared somehow, am I doig the wrog thing?

**Comment by RavinMaddHatter** [comment]
I have never seen that error try the latest release.. The preview one from
yesterday in the release section
