### ISSUE TITLE
Big Build Error 1.21.20

### ISSUE THREAD

**Issue by PrPunk** [RavinMaddHatter/Structura#227]
When exporting a big build mode structure, it gives me this error whenloading into the world. When I place an armor stand, it is invisible and posing it does not change anything. I am experienced in the modding field, so if you can't fix the app for lack of information, I can send you what I did, or you could tell me how to fix the texture pack itself.

This error was originally from 1.21.2, but upon updating to 1.21.20, I still recieved the error. I tried to remake the pack, but recieved the same error. I tried updatig the Structura application and restarting it, but I still recieved the same results.

```
[Geometry][error]-minecraft:armor_stand | minecraft:armor_stand | geometry not found?

[Blocks][warning]-Warning: The blocks.json "format_version" field is invalid. "format_version" 1.1.0 will be used.

[Molang][error]-minecraft:armor_stand | binding expression q.item_slot_to_bone_name(c.item_slot) returned a bone name that doesn't exist.

[Molang][error]-minecraft:armor_stand | binding expression q.item_slot_to_bone_name(c.item_slot) did not return a name?
```

Thank you,
      Josiah

**Comment by RavinMaddHatter** [comment]
I can't work out of previews it breaks the world over time.

The update came out while I was at work and the block changed names. It
will be like that for several days until I have time to work on things

**Comment by PrPunk** [comment]
By the way, the coordinates which I placed the build at are -337, 57, -1008. I also attached the generated texture pack and the structure file.
[Zipped Files](https://github.com/user-attachments/files/16607090/New.folder.zip)

**Comment by PrPunk** [comment]
Oh I just saw your reply. I understand, thank you for the response, I will try again in a few days, It if for a project that I will not be working on for a while

**Comment by PrPunk** [comment]
Also, thank you for the work and effort you put in to Structura, I greatly appreciate it and I'm sure the rest of the Minecraft Bedrock community does too.

**Comment by PrPunk** [comment]
Also, sorry to bother you again, but the blocks.json error appears to be from a different texture pack I have installed.
