### ISSUE TITLE
Missing Blocks 

### ISSUE THREAD

**Issue by tonyaghe** [RavinMaddHatter/Structura#228]
x:28 Y:48 Z:29, Block:minecraft:dark_oak_planks, Variant: Default
There is an unsuported block in this world and it was skipped
the same with these blocks:
minecraft:dark_oak_slab
minecraft:dark_oak_log
minecraft:spruce_slab
minecraft:dark_oak_double_slab
minecraft:dark_oak_planks
minecraft:stripped_dark_oak_wood
minecraft:polished_andesite_slab
minecraft:stripped_oak_wood
minecraft:spruce_double_slab
minecraft:polished_andesite
minecraft:dark_oak_fence
minecraft:cyan_wool
minecraft:smooth_sandstone
minecraft:acacia_fence

**Comment by tonyaghe** [comment]
version 1.21.20

**Comment by RavinMaddHatter** [comment]
Yup... This happens every update. I will fix at some point
