### ISSUE TITLE
Not working on realms? 1.21.20

### ISSUE THREAD

**Issue by TnTIIDarkness** [RavinMaddHatter/Structura#229]
ive only ever made maybe 4 or 5 packs, new to this app, made a pack today, works fine in single player on my friends realm it used to work before 1.21.20, in this latest update it doesn't show up at all? maybe im doing something wrong xD sorry!

**Comment by RavinMaddHatter** [comment]
Your friends realm has a pack that changes armor stands and disables
structura... This has been extensively tested on realms without packs.

**Comment by TnTIIDarkness** [comment]
Did a little bit of testing as we really want structura to work, I had him share his screen and turn off the behaviour packs (vein miner & one player sleep), we left the texture pack as its a custom one i made and the same one i use in single player, the pack works in my single player but still not on the realm

**Comment by TnTIIDarkness** [comment]
I wish that was the issue, would be a simple fix. Sadly no we don't have force packs enabled, great theory though thank you so much for looking into this, I feel like such a bother!

Genuinely think its got something to do with the state of mc realms atm and nothing to do with structura, maybe, although I literally know nothing so XD

**Comment by RavinMaddHatter** [comment]
Honestly it is just a texture pack... Not sure how this would be Broken
realms

**Comment by TnTIIDarkness** [comment]
realms sometimes still forcing packs even when option is not ticked, issue discovered since 1.21.20

foxy no tails marker pack conflicts with structura packs if placed above structura packs, when placed below both packs work in tandem. the realm bug was what caused my issue not structura.

closing as resolved, opening another ticket on Mojang's jira.
