### ISSUE TITLE
Installing Structura on Minecraft Bedrock

### ISSUE THREAD

**Issue by Wolfknight777** [RavinMaddHatter/Structura#231]
Just recently hearing about this, I've looked around for the actual mod that you install on bedrock for the block mentioned in the videos. I don't know where to look, and I already have the .exe downloaded. How can I get Structura blocks on my game now?

**Comment by Wolfknight777** [comment]
I opened the .exe, got on game, did the command and got error.

**Comment by RavinMaddHatter** [comment]
The exe doesn't interface with the game. Watch the videos
