### ISSUE TITLE
Unhandled exception after launching multiple times

### ISSUE THREAD

**Issue by Fusionlight13** [RavinMaddHatter/Structura#233]
I have a recurring issue where, after installing the .exe file and running it a couple of times, I encounter a traceback error on my next attempt. When I delete the file and reinstall it, I can run it without errors for a few more times before the problem reappears. Essentially, after running it twice, the next run results in a traceback error. If I delete it and reinstall, the error doesn't occur for several additional runs. Here is the error: 

Traceback (most recent call last):
  File "structura.py", line 5, in <module>
  File "updater.py", line 18, in update
PermissionError: [Errno 13] Permission denied: 'lookup_temp.zip'

**Comment by RavinMaddHatter** [comment]
Run it from a folder where it has permissions to write files

**Comment by Fusionlight13** [comment]
Wow, I'm an idiot. Thank you lol
