### ISSUE TITLE
Suggestion: Support higher resolution textures

### ISSUE THREAD

**Issue by nether-cat** [RavinMaddHatter/Structura#237]
Would it be possible to support higher resolution textures for the ghost blocks?

I'd actually love to use this with a texture pack that uses a 32x32 resolution, but it's unsurprisingly not working.

I would even dive deeper into the code personally, try to implement it myself and submit a PR. However, I figured it would be a sane thing to directly consult you in advance, as you might already know of limitations given by the technical workings of the armor stand, its geometry or the texture map that's being generated for the resource pack, that I wouldn't be aware of before spending many hours.

What do you think? :)

**Comment by RavinMaddHatter** [comment]
It is allot of work to do that

**Comment by nether-cat** [comment]
I ain't afraid of that. The improvement would be enormous, as it's really confusing to build with a ghost model when the actual texture pack differs a lot. There's little explanation/documentation in your code, though. If you find just a few minutes, maybe you could give me a few hints/tips where to start. I find it hard to figure out how Structura's resource pack even utilizes the armor stand's model rendering / UV mapping to begin with. No rush, though... ;-)

Your tool is very awesome! I'd be too happy if I could help build support for higher res textures.

**Comment by RavinMaddHatter** [comment]
It added a bunch of custom bones to the bones get a custom texture from the
single uv file made from the files in the pack
