### ISSUE TITLE
What is in this program?

### ISSUE THREAD

**Issue by Djwhitelion** [RavinMaddHatter/Structura#239]
I used this exe at work and it got flagged and my pc for locked out of the network. While yes you should not do anything personal on a work pc. I did after a scan get two ransomware messeges on the pc. 
There is something with this program that promts this

**Comment by RavinMaddHatter** [comment]
Python executibles have a high false positive rate for Malware.. you can
look through the code.

**Comment by Djwhitelion** [comment]
Then i have something to say to it atleast. The fault is mine for trying it at work. Maby. Just maby add a warning about the probability of a high risk of false positives because of the format? Just a thought. 
The fault is still all mine.

**Comment by RavinMaddHatter** [comment]
I am trying to get away from exe. Honestly, you shouldn't. Trust me unless
you have reason to. I could make malware and tell you that.. I do say in
the first video that you shouldn't trust random strangers on the internet

**Comment by Djwhitelion** [comment]
Haha. And this is why i am so up front on saying its my fault. 🤣👍
