### ISSUE TITLE
Import *schematic files that are used in java blueprints

### ISSUE THREAD

**Issue by Rayth** [RavinMaddHatter/Structura#24]
Can we get the ability to import *.schematic files that are used in MCEdit for Java worlds

**Comment by RavinMaddHatter** [comment]
For anyone looking to do the same the current work around is to open java, convert the schematic to a world using the schematic tool. save the world and convert to bedrock, make a structure block and import it to bedrock.

**Comment by RavinMaddHatter** [comment]
After digging in.... I cant really support the 2 sets of block names... java and bedrock blocks (inside of the game files) do not have common naming... It would be a huge pain to implement this and it would mean maintaining 2 copies for all blocks... and keeping up with change logs for 2 different games. I can either make it work better for bedrock and keep up with mojang or do this..

I am going to focus on bedrock and ignore java.
