### ISSUE TITLE
When pack creator throws a terminating error, the structure folder with the pack manifest stays

### ISSUE THREAD

**Issue by ForestOfGold** [RavinMaddHatter/Structura#28]
Mostly self-explanatory. When the pack creator fails, the folder with the manifest.json stays in the main "Structura" folder.

![image](https://user-images.githubusercontent.com/77603428/105645249-4a7c0080-5e4f-11eb-930b-f110b5f23848.png)

![image](https://user-images.githubusercontent.com/77603428/105645287-83b47080-5e4f-11eb-8443-b077a41c79d7.png)

**Comment by RavinMaddHatter** [comment]
I had an error in my error handling... i think it is betternow. much less likely to fail now

**Comment by 0ld-guy** [comment]
i think i had this same issue when using lily pads in the structure file, Structura didnt create the pack but did create this json file manifest,

**Comment by RavinMaddHatter** [comment]
This should be fixed in 1.3
