### ISSUE TITLE
List of unsupported blocks found by v1.1.1 Pre

### ISSUE THREAD

**Issue by ForestOfGold** [RavinMaddHatter/Structura#29]
List of unsupported blocks as found by the v1.1.1 Pre-Release (in my "Everything" structure):
- stonecutter_block (I believe this is because of the spinning blade)
- cactus
- seagrass
- kelp
- reeds
- waterlily
- (seagrass mentioned twice more for tall version)

Full Block List: [Everything block list.txt](https://github.com/RavinMaddHatter/Structura/files/5863460/Everything.block.list.txt)

**Comment by RavinMaddHatter** [comment]
I think this is fixed in my current dev branch

**Comment by RavinMaddHatter** [comment]
Closing as we test 1.1.2 These seem to be good.
