### ISSUE TITLE
List of blocks that need updated geometry

### ISSUE THREAD

**Issue by ForestOfGold** [RavinMaddHatter/Structura#30]
This will be a long list- I'll update it as things get patched. This list was made in the v1.1.1 Pre-Release Many of these have textures different to what they should and that will be analyzed after they're fixed since their textures may also be fixed with correct geometry.
```
- mob heads 
- sea pickles
- ground-mounted banner (only block with hitbox)
- wall-mounted banner (render as a wall in the block with the hitbox)
- chain
- one-high flowers (including wither rose)
- flowing water (Currently banned)
- flowing lava (Currently banned)
- fence posts
- fence gates
- doors
- iron bars
- glass panes
- beds
- campfire
- soul campfire
- brewing stand
- crimson roots
- warped roots
- coral
- coral fans
- turtle eggs
- dragon egg
- fern
- tall fern
- grass
- tall grass
- nether sprouts
- brown/red mushroom
- crimson/warped fungus
- sweet berry bush
- cake
- saplings
- crops
- nether wart
- vines
- weeping/twisting vines
- dead bush
- bamboo sprout
- bamboo (multiple tall texture) 
- lever
- buttons
- cocoa bean
- string
- tripwire hook
- bell (ground and wall-mounted)
- fire
- soul fire
- piston heads
- end rods
- conduit
- snow layer
- cobweb
- chorus plant/flower (Doesn't matter imho, but still a bug)
- anvil
- grindstone
- enchantment table
- lectern
- chest/trapped chest/ender chest (Also doesn't matter imho, but still bug and will show the ghost block when you place a chest over it)
- all pressure plates except spruce and stone
- grounded signs
- wall-mounted signs (render as wall)
- flower pot
- portal (nether)
- end portal frame
- end portal
- end gateway
- bubble column
- soul sand (same issue as chests)
- repeater (currently trapdoor)
- comparator (currently trapdoor)
- dirt pat
- beacon
- farmland
- trapdoors (too thin)
- composter
- cauldron
- lit redstone torch
- torch
- soul torch
- ladder
```
I believe this is everything. Check out the list of blocks I checked here: [Everything block list.txt](https://github.com/RavinMaddHatter/Structura/files/5863540/Everything.block.list.txt)

If a contributor could make a comment of the patched ones I can edit the list most accurately. I'd like to keep "hack fixes" out of this list if possible so you have a full list of what needs to be changed.

Reference photo:  ![image](https://user-images.githubusercontent.com/77603428/105648861-8ff5f900-5e62-11eb-8431-cb61742e58d6.png)

**Comment by ForestOfGold** [comment]
What hackfixes are there currently so I can add them? I can think of a couple: Daylight sensors as half slabs and repeaters as trapdoors.

**Comment by RavinMaddHatter** [comment]
I think i patched the daylight sensor. If you do patch can you put the structure file in a "unit test folder". 

I also added a "hacks.json" to the lookups... i pushed it to my dev branch for now

**Comment by RavinMaddHatter** [comment]
Structura 1.3 will allow for this to happen

**Comment by RavinMaddHatter** [comment]
I broke this into individual tickets. I think i will close this one for now. It is easier to work with multiple tickets
