### ISSUE TITLE
Texture bug type: Mixed sides

### ISSUE THREAD

**Issue by ForestOfLight** [RavinMaddHatter/Structura#31]
A temporary fix was recently made for droppers/dispensers/observers showing multiple sides with a hole. It looks like blocks with 6 rotations with more than 3 textures are affected. A few other blocks have this issue. Assume blocks without the correct geometry are currently excluded.
```
Actually important:
- observers
- droppers
- dispensers
- impulse, repeating, and chain command blocks

- cauldrons (water and lava)
- redstone
- rails

Random blocks with incorrect texture rotations that probably don't need a change:
Might not bother to even make this list because it's just visual correctness and doesn't help the user.
```
Example: 
![image](https://user-images.githubusercontent.com/77603428/105675856-9013ea00-5e9e-11eb-9579-c5d603823568.png)
![image](https://user-images.githubusercontent.com/77603428/105675896-9b671580-5e9e-11eb-83ff-56ec4e796190.png)

**Comment by RavinMaddHatter** [comment]
This is now seperate tickets.
