### ISSUE TITLE
cant see the clearly and suggest it to be more transparent

### ISSUE THREAD

**Issue by TimothyGrass** [RavinMaddHatter/Structura#37]

**Comment by HaryTheDuck** [comment]
For me at least it is transparent enough, I don't see the problem of making it more transparent. Maybe if there is something like a slider to make it more or less transparent(again this might be hard to do)

**Comment by TimothyGrass** [comment]
> For me at least it is transparent enough, I don't see the problem of making it more transparent. Maybe if there is something like a slider to make it more or less transparent(again this might be hard to do)

This is like a suggestion from Chinese players and maybe he is having some problem on looking at the model

**Comment by ForestOfGold** [comment]
This is a feature (transparency slider) in the v1.1.1 Pre-Release and will likely be in the next full release.

**Comment by RavinMaddHatter** [comment]
Will be in the next release, as it is a UI change i dont want to drop it on people with out some sort of video to explain the changes or at least some documentation changes.
 you can see it if you click the button under releases and click pre-release 1.1.1 git hub gently hides pre-releases

**Comment by RavinMaddHatter** [comment]
Closing as i have this preped for next release
