### ISSUE TITLE
For easier water placement

### ISSUE THREAD

**Issue by ForestOfLight** [RavinMaddHatter/Structura#38]
Since flowing water will exist anyway when you place a source, why not ban flowing water from being part of structures so players only see water sources? This makes it much easier for players to know where to place the sources.

**Comment by RavinMaddHatter** [comment]
I will do that tonight, look up flowing water and lava and put them in the banned list.


Later when/if we support layers we can remove it from the banned list.

**Comment by RavinMaddHatter** [comment]
Needs to get the water level
