### ISSUE TITLE
Blocks that need extra data to exist in their correct form

### ISSUE THREAD

**Issue by ForestOfLight** [RavinMaddHatter/Structura#40]
Some blocks show up as they would when they have a data value of 0, but need a different one to show correctly. Here are a few blocks that need that extra data value to exist in their correct form:
```
Texture changes:
- doors (except crimson and warped)
- infested stone
- quartz blocks (except quartz bricks)
- dirt (for coarse dirt)
- mushroom blocks
- pumpkins (for carved and jack-o-lantern)
- purpur blocks
- coral blocks
- coral
- wet sponge
- oak, spruce, birch, and jungle leaves show up as oak, while acacia and dark oak show up as acacia (try pick-block on them as well)
- saplings
- one-high flowers (excluding dandelion and wither rose)
- two-high flowers
- two-high grass/fern
- seagrass (likely)
- rails
- daylight sensor (night mode)
- campfire/soul campfire (put out)
(- structure blocks)
-- Those above are most useful, the rest are quality of life --
- colored beds (if they don't already)
(- colored banners (colors not in immediate data values))
- crops (for growth)
- nether wart
- cocoa bean
- sweet berry bush
- composter?
- cauldron?
- respawn anchor (up to you, not super useful imo)
(- skulls (mob types not in immediate data values))
- piston/sticky piston

Geometry changes:
- doors (open state)
- rails (all types)
- snow layers
- sea pickles
- turtle eggs
- crops?
- cake
- composter?
- cauldron?
- repeater
- lever (switched on/off)
- flowing water (currently banned)
- flowing lava (currently banned)
- piston/sticky piston
```
Some blocks already have this function, such as the sandstone and red sandstone types. 
This issue is also a little sketchy because lots of blocks have their data values assigned to rotations. Something to maneuver around unless fully embraced. This report does not include blocks that purely need rotation changes.

Example of a texture change:
![image](https://user-images.githubusercontent.com/77603428/105804013-92844b80-5f53-11eb-88ed-6c8d05b044f2.png)
![image](https://user-images.githubusercontent.com/77603428/105804036-9fa13a80-5f53-11eb-867f-54b56455111e.png)

Example of a geometry change:
![image](https://user-images.githubusercontent.com/77603428/105804106-cf504280-5f53-11eb-963b-957b72b831b1.png)
![image](https://user-images.githubusercontent.com/77603428/105804071-b9db1880-5f53-11eb-9d1a-1b19b85cad66.png)

**Comment by RavinMaddHatter** [comment]
FYI the "data" is really different than from commands. The best way to  "see" what data is in it is to look in "NBTStudio"
https://github.com/tryashtar/nbt-studio
you may pull your hair out... as the naming it HORRIBLE. Thanks mojang.

**Comment by ForestOfGold** [comment]
Aren't NBT tags different from `data:int`?
/give @p quartz_block 1 ->2<-

**Comment by RavinMaddHatter** [comment]
I dont get the data values. i get the nbt values from the structure. And it is all over the place

**Comment by RavinMaddHatter** [comment]
I think this should be broken into individual tickets, i may work on that in a bit, If they are then someone can claim them and work on them 1x1

**Comment by RavinMaddHatter** [comment]
Closing as i think they are all in individual tickets now.
