### ISSUE TITLE
Better view

### ISSUE THREAD

**Issue by OpxGaming** [RavinMaddHatter/Structura#41]
So when playing I sometimes cant see if I place or havent place the block. So was wondering on maybe having a better view on the blocks or having it where if a wrong block turn red to indicate if wrong block or if a dropper of dispenser wrong direction.

**Comment by RavinMaddHatter** [comment]
I don't believe it is possible to do without commands and a bunch of lag. The resource pack doesnt have access to the name of the blocks in the world, and there for cant actually see what block is placed where, what direction that block is facing, or any of the information that would allow me to do that.

Even with commands i dont think it is possible for me to verify direction in BE. If it gets added in a future update i will gladly look into it. But as it stands right now the resource pack simply does not have access to the information required to do this type of action.
