### ISSUE TITLE
Put structure names in pack description

### ISSUE THREAD

**Issue by ForestOfLight** [RavinMaddHatter/Structura#43]
(v1.1.2 Pre-Release) Put the structure/nametag names in the description of the pack rather than creating a new .txt file. Easier viewing and file management. In the case that the tag names have too many characters to fit in the description, then create a .txt as well.

**Comment by RavinMaddHatter** [comment]
I completely agree with this. I wanted to get the feature out last night so we could get some testing under it.. so i did the quick thing and dumped it in a text file

**Comment by RavinMaddHatter** [comment]
Finally got around to fixing this for next release
