### ISSUE TITLE
Observer Arrow Bug

### ISSUE THREAD

**Issue by SommZD** [RavinMaddHatter/Structura#52]
The triangular arrow on the bottom face of observers is facing the opposite direction that it should be. The pointed end of the triangle should face the direction of the signal output. The arrow on the top of the observers is correct.
![Minecraft 2_22_2021 9_27_42 PM](https://user-images.githubusercontent.com/79496862/108802156-d8cdca00-7554-11eb-8dc5-292d033b2b9c.png)

**Comment by RavinMaddHatter** [comment]
Fixed in structura 1.3
