### ISSUE TITLE
version 32-bits for structura ???

### ISSUE THREAD

**Issue by superiaro** [RavinMaddHatter/Structura#55]
Hello ! my problem is that I don't have a computer running in a 64-bits version and I would like to know if it would be possible to create a 32-bits version. Thank you very much for creating structura because it's really what I needed to reproduce complicated buildings and redstone system on bedrock but for the moment I can't... Keep on developing this I support you a lot !

**Comment by RavinMaddHatter** [comment]
Ohh build a version with 32 bit compiler. i will work on this soon

**Comment by FvA-prog** [comment]
Sorry, where can I download the version for 32 bit OS?
