### ISSUE TITLE
Feature Request: Ability to rotate structure adding model

### ISSUE THREAD

**Issue by hgabreu** [RavinMaddHatter/Structura#98]
Just like it is possible to change the offsets while adding a structure to the model list. It would be very helpful to be able to rotate / reorient the structure so that the one can pick the expected/natural orientation when placing the armor stand.

Is there a workaround for this that does not require re-constructing the entire build in the correct orientation?

ps: I know I can rotate / change the placement of the armor stand. I'm just looking for a way to set the correct "natural" position.

**Comment by RavinMaddHatter** [comment]
There is a rotate feature when loading a structure. So you can load it in
game and rotate it in 90 degree increments.

**Comment by hgabreu** [comment]
I do not know how I missed that. Thanks

For the "blind" like me: When loading a structure in with the structure_block in load mode, there's a rotate option.
